language: python
install:
  - pip install bashate
  - pip install rstcheck
script:
  - rstcheck README.rst
  - bashate install_dhcp.sh
  - bashate set_interface.sh
  - bashate install_dns.sh
  - bashate set_nat.sh
  - bashate set_pxe_fog.sh
